export const COUNTRIES = [
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Jordan',
  'Lebanon',
  'Iraq',
  'Iran',
  'Israel',
  'Palestine',
  'Syria',
  'Yemen',
  'Egypt',
  'Turkey',
  'United States',
  'United Kingdom',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Switzerland',
  'Canada',
  'Australia',
  'Japan',
  'China',
  'India',
  'Singapore',
  'Hong Kong',
  'South Korea',
  'Brazil',
  'Mexico',
  'Russia',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Morocco',
  'Pakistan',
  'Indonesia',
  'Malaysia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Austria',
  'Belgium',
  'Ireland',
  'Portugal',
  'Greece',
  'Czech Republic',
  'New Zealand',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Luxembourg',
  'Taiwan',
  'Hungary',
  'Romania',
  'Ukraine',
  'Slovakia',
  'Croatia',
  'Slovenia',
  'Bulgaria',
  'Serbia',
  'Tunisia',
  'Algeria',
  'Libya',
  'Ghana',
  'Ethiopia',
  'Tanzania',
  'Uganda',
  'Zimbabwe',
  'Zambia',
  'Mozambique',
  'Angola',
  'Ivory Coast',
  'Senegal',
  'Cameroon',
  'DR Congo',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Myanmar',
  'Cambodia',
  'Laos',
  'Mongolia',
  'Kazakhstan',
  'Uzbekistan',
  'Azerbaijan',
  'Georgia',
  'Armenia',
  'Afghanistan',
  'Costa Rica',
  'Panama',
  'Puerto Rico',
  'Dominican Republic',
  'Guatemala',
  'Ecuador',
  'Bolivia',
  'Paraguay',
  'Uruguay',
  'Venezuela',
  'Cuba',
  'Jamaica',
  'Trinidad and Tobago',
  'Bahamas',
  'Bermuda',
  'Iceland',
  'Malta',
  'Cyprus',
  'Monaco',
  'Liechtenstein',
  'Andorra',
  'San Marino',
  'Vatican City'
].sort();

export const COUNTRY_CENTROIDS: Record<string, { lat: number; lng: number }> = {
  'united arab emirates': { lat: 24.4539, lng: 54.3773 },
  'uae': { lat: 24.4539, lng: 54.3773 },
  'saudi arabia': { lat: 23.8859, lng: 45.0792 },
  'qatar': { lat: 25.3548, lng: 51.1839 },
  'kuwait': { lat: 29.3759, lng: 47.9774 },
  'bahrain': { lat: 26.0667, lng: 50.5577 },
  'oman': { lat: 21.4735, lng: 55.9754 },
  'jordan': { lat: 30.5852, lng: 36.2384 },
  'lebanon': { lat: 33.8547, lng: 35.8623 },
  'iraq': { lat: 33.2232, lng: 43.6793 },
  'iran': { lat: 32.4279, lng: 53.6880 },
  'israel': { lat: 31.0461, lng: 34.8516 },
  'palestine': { lat: 31.9522, lng: 35.2332 },
  'syria': { lat: 34.8021, lng: 38.9968 },
  'yemen': { lat: 15.5527, lng: 48.5164 },
  'egypt': { lat: 26.8206, lng: 30.8025 },
  'turkey': { lat: 38.9637, lng: 35.2433 },
  'united states': { lat: 37.0902, lng: -95.7129 },
  'united kingdom': { lat: 55.3781, lng: -3.4360 },
  'germany': { lat: 51.1657, lng: 10.4515 },
  'france': { lat: 46.2276, lng: 2.2137 },
  'italy': { lat: 41.8719, lng: 12.5674 },
  'spain': { lat: 40.4637, lng: -3.7492 },
  'netherlands': { lat: 52.1326, lng: 5.2913 },
  'switzerland': { lat: 46.8182, lng: 8.2275 },
  'canada': { lat: 56.1304, lng: -106.3468 },
  'australia': { lat: -25.2744, lng: 133.7751 },
  'japan': { lat: 36.2048, lng: 138.2529 },
  'china': { lat: 35.8617, lng: 104.1954 },
  'india': { lat: 20.5937, lng: 78.9629 },
  'singapore': { lat: 1.3521, lng: 103.8198 },
  'hong kong': { lat: 22.3193, lng: 114.1694 },
  'south korea': { lat: 35.9078, lng: 127.7669 },
  'brazil': { lat: -14.2350, lng: -51.9253 },
  'mexico': { lat: 23.6345, lng: -102.5528 },
  'russia': { lat: 61.5240, lng: 105.3188 },
  'south africa': { lat: -30.5595, lng: 22.9375 },
  'nigeria': { lat: 9.0820, lng: 8.6753 },
  'kenya': { lat: -0.0236, lng: 37.9062 },
  'morocco': { lat: 31.7917, lng: -7.0926 },
  'pakistan': { lat: 30.3753, lng: 69.3451 },
  'indonesia': { lat: -0.7893, lng: 113.9213 },
  'malaysia': { lat: 4.2105, lng: 101.9758 },
  'thailand': { lat: 15.8700, lng: 100.9925 },
  'vietnam': { lat: 14.0583, lng: 108.2772 },
  'philippines': { lat: 12.8797, lng: 121.7740 },
  'sweden': { lat: 60.1282, lng: 18.6435 },
  'norway': { lat: 60.4720, lng: 8.4689 },
  'denmark': { lat: 56.2639, lng: 9.5018 },
  'finland': { lat: 61.9241, lng: 25.7482 },
  'poland': { lat: 51.9194, lng: 19.1451 },
  'austria': { lat: 47.5162, lng: 14.5501 },
  'belgium': { lat: 50.5039, lng: 4.4699 },
  'ireland': { lat: 53.1424, lng: -7.6921 },
  'portugal': { lat: 39.3999, lng: -8.2245 },
  'greece': { lat: 39.0742, lng: 21.8243 },
  'czech republic': { lat: 49.8175, lng: 15.4730 },
  'new zealand': { lat: -40.9006, lng: 174.8860 },
  'argentina': { lat: -38.4161, lng: -63.6167 },
  'chile': { lat: -35.6751, lng: -71.5430 },
  'colombia': { lat: 4.5709, lng: -74.2973 },
  'peru': { lat: -9.1900, lng: -75.0152 },
  'luxembourg': { lat: 49.8153, lng: 6.1296 },
  'taiwan': { lat: 23.6978, lng: 120.9605 },
  'hungary': { lat: 47.1625, lng: 19.5033 },
  'romania': { lat: 45.9432, lng: 24.9668 },
  'ukraine': { lat: 48.3794, lng: 31.1656 },
};

export function getCountryCentroid(country: string): { lat: number; lng: number } | null {
  const key = country.toLowerCase().trim();
  return COUNTRY_CENTROIDS[key] || null;
}

export const COUNTRY_ALIASES: Record<string, string> = {
  'uae': 'United Arab Emirates',
  'u.a.e.': 'United Arab Emirates',
  'emirates': 'United Arab Emirates',
  'ksa': 'Saudi Arabia',
  'kingdom of saudi arabia': 'Saudi Arabia',
  'uk': 'United Kingdom',
  'u.k.': 'United Kingdom',
  'great britain': 'United Kingdom',
  'britain': 'United Kingdom',
  'england': 'United Kingdom',
  'usa': 'United States',
  'u.s.a.': 'United States',
  'u.s.': 'United States',
  'us': 'United States',
  'america': 'United States',
  'united states of america': 'United States',
  'prc': 'China',
  "people's republic of china": 'China',
  'rok': 'South Korea',
  'republic of korea': 'South Korea',
  'korea': 'South Korea',
  'rsa': 'South Africa',
  'republic of south africa': 'South Africa',
  'ussr': 'Russia',
  'russian federation': 'Russia',
  'holland': 'Netherlands',
  'the netherlands': 'Netherlands',
  'czech': 'Czech Republic',
  'czechia': 'Czech Republic',
  'hk': 'Hong Kong',
  'singapore city': 'Singapore',
  'drc': 'DR Congo',
  'democratic republic of congo': 'DR Congo',
  'democratic republic of the congo': 'DR Congo',
  'cote d\'ivoire': 'Ivory Coast',
  'côte d\'ivoire': 'Ivory Coast',
};

export const CITY_TO_COUNTRY: Record<string, string> = {
  'dubai': 'United Arab Emirates', 'abu dhabi': 'United Arab Emirates', 'sharjah': 'United Arab Emirates',
  'ajman': 'United Arab Emirates', 'ras al khaimah': 'United Arab Emirates', 'fujairah': 'United Arab Emirates',
  'al ain': 'United Arab Emirates', 'umm al quwain': 'United Arab Emirates',
  'riyadh': 'Saudi Arabia', 'jeddah': 'Saudi Arabia', 'jidda': 'Saudi Arabia', 'dammam': 'Saudi Arabia',
  'mecca': 'Saudi Arabia', 'makkah': 'Saudi Arabia', 'medina': 'Saudi Arabia', 'madinah': 'Saudi Arabia',
  'khobar': 'Saudi Arabia', 'al khobar': 'Saudi Arabia', 'jubail': 'Saudi Arabia', 'tabuk': 'Saudi Arabia',
  'neom': 'Saudi Arabia', 'yanbu': 'Saudi Arabia', 'taif': 'Saudi Arabia', 'dhahran': 'Saudi Arabia',
  'doha': 'Qatar', 'lusail': 'Qatar', 'al wakrah': 'Qatar',
  'kuwait city': 'Kuwait', 'hawalli': 'Kuwait',
  'manama': 'Bahrain', 'muharraq': 'Bahrain', 'riffa': 'Bahrain',
  'muscat': 'Oman', 'salalah': 'Oman', 'sohar': 'Oman', 'nizwa': 'Oman',
  'amman': 'Jordan', 'aqaba': 'Jordan',
  'beirut': 'Lebanon', 'tripoli': 'Lebanon',
  'baghdad': 'Iraq', 'erbil': 'Iraq', 'basra': 'Iraq', 'sulaymaniyah': 'Iraq',
  'tehran': 'Iran', 'isfahan': 'Iran', 'shiraz': 'Iran', 'tabriz': 'Iran', 'mashhad': 'Iran',
  'tel aviv': 'Israel', 'jerusalem': 'Israel', 'haifa': 'Israel',
  'damascus': 'Syria', 'aleppo': 'Syria',
  'sanaa': 'Yemen', 'aden': 'Yemen',
  'cairo': 'Egypt', 'alexandria': 'Egypt', 'giza': 'Egypt', 'luxor': 'Egypt', 'sharm el sheikh': 'Egypt',
  'istanbul': 'Turkey', 'ankara': 'Turkey', 'izmir': 'Turkey', 'antalya': 'Turkey',
  'london': 'United Kingdom', 'manchester': 'United Kingdom', 'birmingham': 'United Kingdom',
  'edinburgh': 'United Kingdom', 'glasgow': 'United Kingdom', 'leeds': 'United Kingdom',
  'liverpool': 'United Kingdom', 'bristol': 'United Kingdom', 'cardiff': 'United Kingdom',
  'new york': 'United States', 'los angeles': 'United States', 'chicago': 'United States',
  'houston': 'United States', 'san francisco': 'United States', 'miami': 'United States',
  'boston': 'United States', 'seattle': 'United States', 'dallas': 'United States',
  'atlanta': 'United States', 'washington': 'United States', 'washington dc': 'United States',
  'washington d.c.': 'United States', 'denver': 'United States', 'phoenix': 'United States',
  'philadelphia': 'United States', 'san diego': 'United States', 'austin': 'United States',
  'new york city': 'United States', 'nyc': 'United States',
  'berlin': 'Germany', 'munich': 'Germany', 'frankfurt': 'Germany', 'hamburg': 'Germany',
  'dusseldorf': 'Germany', 'düsseldorf': 'Germany', 'cologne': 'Germany', 'stuttgart': 'Germany',
  'paris': 'France', 'lyon': 'France', 'marseille': 'France', 'nice': 'France', 'toulouse': 'France',
  'rome': 'Italy', 'milan': 'Italy', 'florence': 'Italy', 'naples': 'Italy', 'turin': 'Italy', 'venice': 'Italy',
  'madrid': 'Spain', 'barcelona': 'Spain', 'seville': 'Spain', 'valencia': 'Spain', 'malaga': 'Spain',
  'amsterdam': 'Netherlands', 'rotterdam': 'Netherlands', 'the hague': 'Netherlands', 'utrecht': 'Netherlands',
  'zurich': 'Switzerland', 'geneva': 'Switzerland', 'bern': 'Switzerland', 'basel': 'Switzerland', 'lausanne': 'Switzerland',
  'toronto': 'Canada', 'vancouver': 'Canada', 'montreal': 'Canada', 'calgary': 'Canada', 'ottawa': 'Canada',
  'sydney': 'Australia', 'melbourne': 'Australia', 'brisbane': 'Australia', 'perth': 'Australia', 'adelaide': 'Australia',
  'tokyo': 'Japan', 'osaka': 'Japan', 'kyoto': 'Japan', 'yokohama': 'Japan', 'nagoya': 'Japan',
  'beijing': 'China', 'shanghai': 'China', 'shenzhen': 'China', 'guangzhou': 'China',
  'chengdu': 'China', 'hangzhou': 'China', 'nanjing': 'China', 'wuhan': 'China', 'tianjin': 'China',
  'mumbai': 'India', 'delhi': 'India', 'new delhi': 'India', 'bangalore': 'India', 'bengaluru': 'India',
  'chennai': 'India', 'hyderabad': 'India', 'pune': 'India', 'kolkata': 'India', 'ahmedabad': 'India',
  'gurgaon': 'India', 'gurugram': 'India', 'noida': 'India',
  'seoul': 'South Korea', 'busan': 'South Korea', 'incheon': 'South Korea',
  'sao paulo': 'Brazil', 'são paulo': 'Brazil', 'rio de janeiro': 'Brazil', 'brasilia': 'Brazil',
  'mexico city': 'Mexico', 'guadalajara': 'Mexico', 'monterrey': 'Mexico',
  'moscow': 'Russia', 'saint petersburg': 'Russia', 'st petersburg': 'Russia',
  'johannesburg': 'South Africa', 'cape town': 'South Africa', 'durban': 'South Africa', 'pretoria': 'South Africa',
  'lagos': 'Nigeria', 'abuja': 'Nigeria', 'port harcourt': 'Nigeria',
  'nairobi': 'Kenya', 'mombasa': 'Kenya',
  'casablanca': 'Morocco', 'rabat': 'Morocco', 'marrakech': 'Morocco', 'marrakesh': 'Morocco',
  'karachi': 'Pakistan', 'lahore': 'Pakistan', 'islamabad': 'Pakistan',
  'jakarta': 'Indonesia', 'surabaya': 'Indonesia', 'bali': 'Indonesia',
  'kuala lumpur': 'Malaysia', 'penang': 'Malaysia', 'johor bahru': 'Malaysia',
  'bangkok': 'Thailand', 'phuket': 'Thailand', 'chiang mai': 'Thailand',
  'ho chi minh city': 'Vietnam', 'hanoi': 'Vietnam', 'saigon': 'Vietnam',
  'manila': 'Philippines', 'cebu': 'Philippines', 'davao': 'Philippines',
  'stockholm': 'Sweden', 'gothenburg': 'Sweden', 'malmö': 'Sweden', 'malmo': 'Sweden',
  'oslo': 'Norway', 'bergen': 'Norway', 'stavanger': 'Norway',
  'copenhagen': 'Denmark', 'aarhus': 'Denmark',
  'helsinki': 'Finland', 'espoo': 'Finland',
  'warsaw': 'Poland', 'krakow': 'Poland', 'kraków': 'Poland', 'gdansk': 'Poland',
  'vienna': 'Austria', 'salzburg': 'Austria', 'graz': 'Austria',
  'brussels': 'Belgium', 'antwerp': 'Belgium', 'ghent': 'Belgium',
  'dublin': 'Ireland', 'cork': 'Ireland', 'galway': 'Ireland',
  'lisbon': 'Portugal', 'porto': 'Portugal',
  'athens': 'Greece', 'thessaloniki': 'Greece',
  'prague': 'Czech Republic', 'brno': 'Czech Republic',
  'auckland': 'New Zealand', 'wellington': 'New Zealand', 'christchurch': 'New Zealand',
  'buenos aires': 'Argentina', 'cordoba': 'Argentina',
  'santiago': 'Chile', 'valparaiso': 'Chile',
  'bogota': 'Colombia', 'bogotá': 'Colombia', 'medellin': 'Colombia', 'medellín': 'Colombia',
  'lima': 'Peru', 'cusco': 'Peru',
  'luxembourg city': 'Luxembourg',
  'taipei': 'Taiwan', 'kaohsiung': 'Taiwan',
  'budapest': 'Hungary',
  'bucharest': 'Romania', 'cluj': 'Romania',
  'kyiv': 'Ukraine', 'kiev': 'Ukraine', 'lviv': 'Ukraine',
  'bratislava': 'Slovakia', 'kosice': 'Slovakia',
  'zagreb': 'Croatia', 'split': 'Croatia', 'dubrovnik': 'Croatia',
  'ljubljana': 'Slovenia',
  'sofia': 'Bulgaria', 'plovdiv': 'Bulgaria',
  'belgrade': 'Serbia', 'novi sad': 'Serbia',
  'tunis': 'Tunisia',
  'algiers': 'Algeria', 'oran': 'Algeria',
  'accra': 'Ghana', 'kumasi': 'Ghana',
  'addis ababa': 'Ethiopia',
  'dar es salaam': 'Tanzania', 'dodoma': 'Tanzania',
  'colombo': 'Sri Lanka',
  'dhaka': 'Bangladesh', 'chittagong': 'Bangladesh',
  'kathmandu': 'Nepal',
  'phnom penh': 'Cambodia',
  'yangon': 'Myanmar', 'rangoon': 'Myanmar',
  'vientiane': 'Laos',
  'panama city': 'Panama',
  'san jose': 'Costa Rica',
  'havana': 'Cuba',
  'montevideo': 'Uruguay',
  'quito': 'Ecuador', 'guayaquil': 'Ecuador',
  'caracas': 'Venezuela',
  'dakar': 'Senegal',
  'luanda': 'Angola',
  'kinshasa': 'DR Congo',
  'kampala': 'Uganda',
  'kigali': 'Rwanda',
  'maputo': 'Mozambique',
  'windhoek': 'Namibia',
  'gaborone': 'Botswana',
  'lusaka': 'Zambia',
  'harare': 'Zimbabwe',
  'monaco': 'Monaco', 'monte carlo': 'Monaco',
};

export function normalizeCountryName(country: string): string {
  if (!country) return 'Unknown';
  
  const trimmed = country.trim();
  const key = trimmed.toLowerCase();
  
  if (COUNTRY_ALIASES[key]) {
    return COUNTRY_ALIASES[key];
  }
  
  if (CITY_TO_COUNTRY[key]) {
    return CITY_TO_COUNTRY[key];
  }
  
  const exactMatch = COUNTRIES.find(c => c.toLowerCase() === key);
  if (exactMatch) {
    return exactMatch;
  }
  
  const partialMatch = COUNTRIES.find(c => c.toLowerCase().includes(key) || key.includes(c.toLowerCase()));
  if (partialMatch) {
    return partialMatch;
  }
  
  const cityPartial = Object.keys(CITY_TO_COUNTRY).find(city => key.includes(city) || city.includes(key));
  if (cityPartial) {
    return CITY_TO_COUNTRY[cityPartial];
  }
  
  return trimmed;
}
